DROP TABLE IF EXISTS tracks;
CREATE TABLE tracks ( 
track_id INT NOT NULL PRIMARY KEY NULL AUTO_INCREMENT,
track_title VARCHAR(300) NOT NULL NULL,
track_duration FLOAT NULL NULL,
track_release_year INT NULL NULL,
original_track TINYINT NULL NULL,
original_artist VARCHAR(100) NULL NULL,
track_album VARCHAR(100) NULL NULL,
track_youtube_url VARCHAR(500) NULL NULL,
track_order INT NULL NULL
);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (4,'Falling From High',10.55,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=59yWnDYuILM',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (5,'Purple Lights',3.41,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=4XxA41d8nVI',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (6,'Octavian',1.35,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=gzo4cz3f72Q',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (7,'Fly through the Ice',2.38,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=bhYeOOugw-w',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (8,'Friday Night Fuckery',5.06,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=FdZWLKXUXIE',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (9,'Old Endings',4.58,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=l1z9trcxFgI',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (10,'Where Did You Sleep Last Night ?',3.58,2019,0,'Lead Belly','Edge of Chaos','https://www.youtube.com/watch?v=GxtGNC9GNz4',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (11,'Winter Child',4.19,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=6GG66Wg76PI',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (12,'Edge of Chaos',2.31,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=LkI4xAzAYeY',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (13,'Levitate',2.29,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=Ry9o3uqGDBw',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (14,'Hurt',4.07,2019,0,'Nine Inch Nails','Edge of Chaos','https://www.youtube.com/watch?v=IBFynoHiEuM',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (15,'On This Shore',4.18,2019,1,NULL,'Edge of Chaos','https://www.youtube.com/watch?v=N0atjkFXpTY',0);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (16,'Dark Angel',NULL,2009,1,NULL,'Dimension 23',NULL,1);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (17,'Cello in a Rush',NULL,2009,1,NULL,'Dimension 23','https://www.youtube.com/watch?v=vQxmv1EdaVI',2);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (18,'On My Way',NULL,2009,1,NULL,'Dimension 23',NULL,3);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (19,'Going Down',NULL,2009,1,NULL,'Dimension 23',NULL,4);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (20,'Diamond Eyes',NULL,2009,1,NULL,'Dimension 23',NULL,5);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (21,'Spider In My Dreams',NULL,2009,1,NULL,'Dimension 23',NULL,6);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (22,'It\'s You I Feel',NULL,2009,1,NULL,'Dimension 23',NULL,7);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (23,'War is Over',NULL,2009,1,NULL,'Dimension 23',NULL,8);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (24,'Killer Dream',NULL,2009,1,NULL,'Dimension 23',NULL,9);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (25,'All You Butterflies',NULL,2009,1,NULL,'Dimension 23',NULL,10);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (26,'I Want to Be Your Star',NULL,2009,1,NULL,'Dimension 23',NULL,11);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (27,'At the Door',NULL,2009,1,NULL,'Dimension 23',NULL,12);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (28,'Dimension 23',NULL,2009,1,NULL,'Dimension 23',NULL,13);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (29,'Nothing\'s Quite Real',NULL,2009,1,NULL,'Dimension 23',NULL,14);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (30,'God and Claus',2.09,2015,1,NULL,NULL,'https://www.youtube.com/watch?v=OOxj_Flo_V4',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (31,'The Lines',8.09,2015,1,NULL,NULL,'https://youtu.be/7hoqLmKgo0Q',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (32,'In the Sky',5.02,2013,1,NULL,NULL,'https://youtu.be/odEJ3-wKIFk',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (33,'Echo Child',4.02,2015,1,NULL,NULL,'https://www.youtube.com/watch?v=Yt7m759yCmU',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (34,'House of the Rising Sun',4.24,2015,0,'The Animals',NULL,'https://www.youtube.com/watch?v=AszoN-FWulQ',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (35,'Morpheus and Gaia',5.3,2015,1,NULL,NULL,'https://youtu.be/300LQyFNDXI',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (36,'River Limbo',7.27,2014,1,NULL,NULL,'https://youtu.be/10n4ypp5Hvk',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (37,'Our Time',7.51,2015,1,NULL,NULL,'https://www.youtube.com/watch?v=r_NMHrwxjZw',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (38,'Second Running Blind: Final Act',1.17,2013,1,NULL,NULL,'https://www.youtube.com/watch?v=sE-6249iGaE',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (39,'Pure as Gold',4.52,2013,1,NULL,NULL,'https://www.youtube.com/watch?v=rFHd-WYvPKk',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (40,'Video Games',4.47,2013,0,'Lana Del Rey',NULL,'https://www.youtube.com/watch?v=zJFGiafb9bE',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (41,'Where We Belong',4.36,2012,1,NULL,NULL,'https://www.youtube.com/watch?v=NzI32-scIvc',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (42,'Stairway to Heaven',8.09,2011,0,'Led Zeppelin',NULL,'https://www.youtube.com/watch?v=vQvnU8kOPME',NULL);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (43,'Crossing through',5.14,2022,1,'undefined','2022 releases','https://www.youtube.com/watch?v=dQw4w9WgXcQ',1);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (44,'Crossing through',5.14,2022,0,'Charles Gosme','Phoenix Rising','https://www.youtube.com/watch?v=dQw4w9WgXcQ',1);
INSERT INTO `` (`track_id`,`track_title`,`track_duration`,`track_release_year`,`original_track`,`original_artist`,`track_album`,`track_youtube_url`,`track_order`) VALUES (45,'The Ugly Song',4.21,2019,0,'','Edge of Chaos','https://www.youtube.com/watch?v=tD9UydDwl0c',1);
